packages:
  - "apps/*"
  - "packages/*"

catalogs:
  tailwindcss:
    clsx: ^2.1.1
    postcss: ^8.5.3
    tailwindcss: ^4.1.6
    tailwind-merge: ^3.2.0
    "@tailwindcss/cli": ^4.1.6
    "@tailwindcss/postcss": ^4.1.6
  react-next:
    next: ^15.3.2
    react: ^19.1.0
    react-dom: ^19.1.0
    lucide-react: ^0.507.0
    "@types/react": ^19.1.3
    "@types/react-dom": ^19.1.3
  typescript:
    tsup: ^8.4.0
    typescript: ^5.8.3
    tsc-alias: ^1.8.16
    "@types/node": ^22.15.17
